// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Counter$Whatever = require("./components/Counter.bs.js");

((
  console.log('Raw JavaScript')
));

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, Counter$Whatever.make("Hello there", /* array */[])), "app");

/*  Not a pure module */
